### ISSUE TITLE
Kill special config format for standard YAML

### ISSUE THREAD

**Issue by jonnor** [the-grid/guv#3]
Main motivation for the custom config was to have a format which was human readable/writeable, and could fold nicely into one line (by making \n and ; equivalent).
Thinking was that config stored as envvar should be single-line.

In practice we are storing the config in a file (checked into git), with newlines for readability, and just setting this directly as the envvar using a little bash script around `heroku config`.

And we'd like to make tools for automatically updating the config files, for instance to get the latest process time/stddev estimates from New Relic or similar collected data.

Getting rid of it for something standard makes these kinds of tools easier.
The semantics of the format could be the same.

**Comment by bergie** [comment]
In case of MsgFlo, I'd actually like to have the guv configuration in graph metadata

**Comment by bergie** [comment]
Potentially related: http://stackoverflow.com/questions/30939057/adding-additional-metadata-to-the-noflo-ui

**Comment by jonnor** [comment]
I think that is best done by have a tool which takes the metadata out of FBP graph and produces a valid guv config file.
