### ISSUE TITLE
Statuspage.io metrics support

### ISSUE THREAD

**Issue by bergie** [the-grid/guv#5]
guv knows the number of in-flight jobs. This could be used for populating metrics to statuspage.io, like for example [Travis does](https://www.traviscistatus.com/):

<img width="867" alt="screen shot 2015-09-23 at 19 21 30" src="https://cloud.githubusercontent.com/assets/3346/10051085/698ae730-6228-11e5-9179-b4d77b0948e9.png">

http://doers.statuspage.io/api/v1/metrics/

**Comment by bergie** [comment]
This is live in guv 0.1.x. To enable metrics support you need to do three things:
- Set your statuspage.io API key to `STATUSPAGE_API_TOKEN` env var
- Set your statuspage page ID to `statuspage` key for `*` role
- Add a `metric` key with the metric ID to those queue definitions you're interested in your guv YAML config

**Comment by jonnor** [comment]
@bergie  Edited comment to add one more step needed
